name: validate

on:
  pull_request:
    branches: ['*']
  push:
    branches: ['*']

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Static Analysis
        uses: pre-commit/action@v3.0.0

      - name: Pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@main
