name: validate

on:
  pull_request:
    branches: ['*']
  push:
    branches: ['*']

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - uses: pre-commit/action@v2.0.0
      - name: cdk synth
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: 'synth'
          working_dir: 'cdk'
        env:
          DOCKER_IMAGE: ${{ env.IMAGE_PATH_AND_TAG }}
