name: validate

on:
  pull_request:
    branches: ['*']
  push:
    branches: ['*']

env:
  IMAGE_PATH_AND_TAG: ghcr.io/sage-bionetworks/data_curator:0.2.8-beta
  AWS_DEFAULT_REGION: 'us-east-1'
  PORT: 3838
  COST_CENTER: 'NO_PROGRAM/000000'
  STACK_NAME_PREFIX: dca-test
  HOST_NAME: dca.dnt-dev.sagebase.org
  HOSTED_ZONE_NAME: dnt-dev.sagebase.org
  HOSTED_ZONE_ID: Z0441843EAHKE7DR12AX

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Static Analysis
        uses: pre-commit/action@v3.0.0

      - name: Install dependencies
        run: pip install -r requirements.txt -r requirements-dev.txt

      - name: Run unit tests
        run: COST_CENTER=${{ env.COST_CENTER }} python -m pytest tests/ -s -v

      - name: cdk synth
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: 'synth'
          working_dir: 'cdk'
        env:
          DOCKER_IMAGE: ${{ env.IMAGE_PATH_AND_TAG }}
